using System.Text;
using IpSync.Models;

namespace IpSync.Services;

public sealed class ReadmeRenderer
{
    public string Render(IpSnapshot snapshot)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# IP Sync");
        builder.AppendLine();
        builder.AppendLine("> This file is generated by the IpSync Windows Service. Manual edits may be overwritten.");
        builder.AppendLine();
        builder.AppendLine($"- Machine: `{EscapeInline(snapshot.MachineName)}`");
        builder.AppendLine($"- Last updated (local): `{snapshot.CapturedAtLocal:yyyy-MM-dd HH:mm:ss zzz}`");
        builder.AppendLine($"- Last updated (UTC): `{snapshot.CapturedAtUtc:yyyy-MM-dd HH:mm:ss 'UTC'}`");
        builder.AppendLine();
        builder.AppendLine("## External IP Addresses");
        builder.AppendLine();
        builder.AppendLine("| Version | Address | Source / Status |");
        builder.AppendLine("| --- | --- | --- |");

        foreach (var externalAddress in snapshot.ExternalAddresses)
        {
            var address = externalAddress.Address is null
                ? "_Unavailable_"
                : $"`{EscapeInline(externalAddress.Address)}`";

            var status = externalAddress.Address is null
                ? EscapeTable(externalAddress.Error ?? "Unavailable")
                : EscapeTable(externalAddress.Source ?? "OK");

            builder.AppendLine($"| {externalAddress.Version} | {address} | {status} |");
        }

        builder.AppendLine();
        builder.AppendLine("## Local Network Addresses");
        builder.AppendLine();

        if (snapshot.LocalAddresses.Count == 0)
        {
            builder.AppendLine("_No active IPv4 or IPv6 addresses were found on non-loopback interfaces._");
        }
        else
        {
            builder.AppendLine("| Version | Address | Prefix | Interface | Type |");
            builder.AppendLine("| --- | --- | ---: | --- | --- |");

            foreach (var localAddress in snapshot.LocalAddresses)
            {
                var prefix = localAddress.PrefixLength?.ToString() ?? "";
                var interfaceName = EscapeTable($"{localAddress.InterfaceName} ({localAddress.InterfaceDescription})");
                builder.AppendLine(
                    $"| {localAddress.Version} | `{EscapeInline(localAddress.Address)}` | {prefix} | {interfaceName} | {EscapeTable(localAddress.NetworkKind)} |");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Service Settings");
        builder.AppendLine();
        builder.AppendLine("- Runs once when the service starts.");
        builder.AppendLine("- Runs again every 10 minutes by default.");
        builder.AppendLine("- Writes this README, commits it, and pushes it only when local network addresses change.");

        return builder.ToString();
    }

    private static string EscapeInline(string value)
    {
        return value.Replace("`", "\\`", StringComparison.Ordinal);
    }

    private static string EscapeTable(string value)
    {
        return value
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
    }
}
